import asyncio
from wizwalker import XYZ, Orient, Client, Keycode
from wizwalker.file_readers.wad import Wad
import math
import struct
from io import BytesIO
from typing import Tuple, Union
from loguru import logger
from src.utils import is_free, is_visible_by_path
from src.paths import advance_dialog_path
from src import walk_nav
from copy import copy

type_format_dict = {
"char": "<c",
"signed char": "<b",
"unsigned char": "<B",
"bool": "?",
"short": "<h",
"unsigned short": "<H",
"int": "<i",
"unsigned int": "<I",
"long": "<l",
"unsigned long": "<L",
"long long": "<q",
"unsigned long long": "<Q",
"float": "<f",
"double": "<d",
}



class TypedBytes(BytesIO):
    def split(self, index: int) -> Tuple["TypedBytes", "TypedBytes"]:
        self.seek(0)
        buffer = self.read(index)
        return type(self)(buffer), type(self)(self.read())
    def read_typed(self, type_name: str):
        type_format = type_format_dict[type_name]
        size = struct.calcsize(type_format)
        data = self.read(size)
        return struct.unpack(type_format, data)[0]



# implemented from https://github.com/PeechezNCreem/navwiz/
# this licence covers the below function
# Boost Software License - Version 1.0 - August 17th, 2003
#
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
#
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

def parse_nav_data(file_data: Union[bytes, TypedBytes]):
    # ty starrfox for remaking this
    if isinstance(file_data, bytes):
        file_data = TypedBytes(file_data)
    vertex_count = file_data.read_typed("short")
    vertex_max = file_data.read_typed("short")
    # unknown bytes
    file_data.read_typed("short")
    vertices = []
    idx = 0
    while idx <= vertex_max - 1:
        x = file_data.read_typed("float")
        y = file_data.read_typed("float")
        z = file_data.read_typed("float")
        vertices.append(XYZ(x, y, z))
        vertex_index = file_data.read_typed("short")
        if vertex_index != idx:
            vertices.pop()
            vertex_max -= 1
        else:
            idx += 1
    edge_count = file_data.read_typed("int")
    edges = []
    for idx in range(edge_count):
        start = file_data.read_typed("short")
        stop = file_data.read_typed("short")
        edges.append((start, stop))
    return vertices, edges

def get_neighbors(vertex: XYZ, vertices: list[XYZ], edges: list[(int, int)]):
    vert_idx = -1
    for v in vertices:
        vert_idx += 1
        if v == vertex:
            break
    if vert_idx == -1:
        # no matching index found, return empty
        return []

    result = []
    for edge in edges:
        if edge[0] == vert_idx:
            result.append(vertices[edge[1]])
    return result


def calc_PointOn3DLine(xyz_1 : XYZ, xyz_2 : XYZ, additional_distance):
    # extends a point on the line created by 2 XYZs by additional_distance. xyz_1 is the origin.
    distance = calc_Distance(xyz_1, xyz_2)
    # distance = math.sqrt((pow(xyz_1.x - xyz_2.x, 2.0)) + (pow(xyz_1.y - xyz_2.y, 2.0)) + (pow(xyz_1.z - xyz_2.z, 2.0)))
    # Doing a rough distance check here since XYZ's aren't always equal even if they have seemingly the same values
    if distance < 1.0:
        return xyz_1
    else:
        n = ((distance - additional_distance) / distance)
        return XYZ(x=((xyz_2.x - xyz_1.x) * n) + xyz_1.x, y=((xyz_2.y - xyz_1.y) * n) + xyz_1.y, z=((xyz_2.z - xyz_1.z) * n) + xyz_1.z)


def are_xyzs_within_threshold(xyz_1 : XYZ, xyz_2 : XYZ, threshold : int = 200):
    # checks if 2 xyz's are within a rough distance threshold of each other. Not actual distance checking, but precision isn't needed for this, this exists to eliminate tiny variations in XYZ when being sent back from a failed port.
    threshold_check = [abs(abs(xyz_1.x) - abs(xyz_2.x)) < threshold, abs(abs(xyz_1.y) - abs(xyz_2.y)) < threshold, abs(abs(xyz_1.z) - abs(xyz_2.z)) < threshold]
    return all(threshold_check)


def calc_squareDistance(xyz_1 : XYZ, xyz_2 : XYZ):
    # calculates the distance between 2 XYZs, but doesn't square root the answer to be much more efficient. Useful for comparing distances, not much else.
    return (pow(xyz_1.x - xyz_2.x, 2.0)) + (pow(xyz_1.y - xyz_2.y, 2.0)) + (pow(xyz_1.z - xyz_2.z, 2.0))


def calc_Distance(xyz_1 : XYZ, xyz_2 : XYZ):
    # calculates the distance between 2 XYZs
    return math.sqrt(calc_squareDistance(xyz_1, xyz_2))


async def calc_FrontalVector(client: Client, xyz : XYZ = None, yaw : float = None, speed_constant : int = 580, speed_adjusted : bool = True, length_adjusted : bool = True):
    # handle if it is adjusted via speed multiplier or just uses the set constant
    if speed_adjusted:
        current_speed = await client.client_object.speed_multiplier()
    else:
        current_speed = 0

    # handles optional xyz param, will default to using the position of the client
    if not xyz:
        xyz = await client.body.position()

    # handles optional yaw paraam, will default to using the yaw of the client
    if not yaw:
        yaw = await client.body.yaw()
    else:
        yaw = yaw

    # adjust the speed constant based on the speed multiplier
    additional_distance = speed_constant * ((current_speed / 100) + 1)

    # calculate point "in front" of XYZ/client using yaw
    frontal_x = (xyz.x - (additional_distance * math.sin(yaw)))
    frontal_y = (xyz.y - (additional_distance * math.cos(yaw)))
    frontal_xyz = XYZ(x=frontal_x, y=frontal_y, z=xyz.z)

    # make a length adjustment since diagonal movements
    if length_adjusted:
        distance = calc_Distance(xyz, frontal_xyz)
        final_xyz = calc_PointOn3DLine(xyz_1=xyz, xyz_2=frontal_xyz, additional_distance=(additional_distance - distance))
    else:
        final_xyz = frontal_xyz

    return final_xyz


# TODO: This has 2 duplicates
async def load_wad(path: str):
    if path is not None:
        return Wad.from_game_data(path.replace("/", "-"))

async def teleport_move_adjust(client: Client, xyz : XYZ, delay : float = 0.7):
    # teleports the client to a given XYZ, and jitters afterward to actually update the position
    if await is_free(client):
        # print("teleport started")
        try:
            await client.teleport(xyz, wait_on_inuse= True, purge_on_after_unuser_fixer = True)
        except:
            pass
        # print("teleport completed")
        await asyncio.sleep(delay)
        await client.send_key(Keycode.A, 0.05)
        await client.send_key(Keycode.D, 0.05)
    else:
        print("not free didn't teleport_move_adjust")
        await asyncio.sleep(0.5)

def rotate_point(origin_xyz : XYZ, point_xyz : XYZ, theta):
    # rotates point_xyz about origin_xyz, by theta degrees counterclockwise. This doesn't take the Z into account, so don't use this for anything that needs the Z to rotate.
    radians = math.radians(theta)
    cos = math.cos(radians)
    sin = math.sin(radians)
    y_diff = point_xyz.y - origin_xyz.y
    x_diff = point_xyz.x - origin_xyz.x
    x = cos * x_diff - sin * y_diff + origin_xyz.x
    y = sin * x_diff + cos * y_diff + origin_xyz.y
    return XYZ(x=x, y=y, z=point_xyz.z)

async def auto_adjusting_teleport(client: Client, quest_position: XYZ = None):
    # DEPRECATED: Uses brute forcing XYZs in an alternating spiral pattern to find usable coords to port to. VERY slow.
    original_zone_name = await client.zone_name()
    original_position = await client.body.position()
    if not quest_position:
        quest_position = await client.quest_position.position()

    adjusted_position = quest_position
    mod_amount = 50
    current_angle = 0
    if await is_free(client):
        await teleport_move_adjust(client, quest_position)
    else:
        return
    while are_xyzs_within_threshold((await client.body.position()), original_position, 50) and await client.zone_name() == original_zone_name:
        if not await is_free(client):
                return
        elif not are_xyzs_within_threshold(original_position, quest_position, 1):
            adjusted_position = calc_PointOn3DLine(original_position, quest_position, mod_amount)
            rotated_position = rotate_point(quest_position, adjusted_position, current_angle)
            if await is_free(client):
                await teleport_move_adjust(client, rotated_position)
            else:
                return
            mod_amount += 100
            current_angle += 92
        else:
            break
            
async def fallback_spiral_tp(client: Client, xyz: XYZ):
    await auto_adjusting_teleport(client, xyz)

#: How long `navmap_tp` waits for a wizard that is not free to become
#: free, in seconds. Zero restores the upstream behaviour of discarding
#: the teleport immediately.
#:
#: `is_free` is three conditions -- loading, in a duel, dialogue box up
#: -- and upstream a `tp` issued while any of them holds is silently
#: dropped on the first line of `navmap_tp`. wizAi's run at rev
#: 1d28f745 is that happening eight times to each of three wizards,
#: within milliseconds of each other and ten seconds apart: the script
#: telling the party to teleport while the game says no, and the party
#: drifting apart as some of the attempts land and others do not.
#:
#: Two of the three conditions are transient. A loading screen ends in
#: seconds and a dialogue box is dismissed in seconds, so waiting a
#: little turns a dropped instruction into a slightly late one. The
#: third is not: a duel lasts minutes and cannot be teleported out of at
#: all, so that one still returns immediately and says so.
TP_FREE_WAIT = 8.0

#: What a zone load is actually allowed to take. `is_loading()` is true
#: for a real transition AND for `PageFlip`, a window that is not a
#: transition at all, so a flag that has not cleared in this long is
#: evidence about the flag rather than about the game.
TP_LOADING_WAIT = 25.0

#: `is_free` folds four different states into one boolean, and the four
#: want four different answers: a duel cannot be waited out, a dialogue
#: box has to be dismissed by somebody, a zone transition clears itself,
#: and a stuck `PageFlip` clears never. Told apart, each can be handled;
#: folded together, all four look like "not now" and the instruction is
#: dropped -- which is the loop that ate five minutes of a real run,
#: nineteen dropped teleports all reporting the same useless sentence.
BLOCK_NONE = ""
BLOCK_DUEL = "duel"
BLOCK_DIALOGUE = "dialogue"
BLOCK_TRANSITION = "transition"
BLOCK_PAGEFLIP = "pageflip"
BLOCK_LOADING = "loading"       # is_loading(), sub-kind unreadable
BLOCK_UNREADABLE = "unreadable"

#: The kinds that mean "the client says it is loading". Only these are
#: ever pushed through, and only after `TP_LOADING_WAIT`.
LOADING_BLOCKS = (BLOCK_TRANSITION, BLOCK_PAGEFLIP, BLOCK_LOADING)

_BLOCK_WORDS = {
    BLOCK_DUEL: "the wizard was in a duel",
    BLOCK_DIALOGUE: "a dialogue box was open",
    BLOCK_TRANSITION: "a zone transition was on screen",
    BLOCK_PAGEFLIP: "the book (PageFlip) was open, which the client "
                    "reports as loading",
    BLOCK_LOADING: "the client reported a loading screen",
    BLOCK_UNREADABLE: "the client would not answer",
}


def describe_block(kind: str) -> str:
    return _BLOCK_WORDS.get(kind, kind or "nothing")


async def _has_child(window, name: str) -> bool:
    try:
        await window.get_child_by_name(name)
    except ValueError:
        return False
    except Exception:
        return False
    return True


async def blocked_by(client) -> str:
    """Which of `is_free`'s conditions is holding, most specific first.

    Deliberately re-derived here rather than read off `is_free`, whose
    answer is a single bool: `is_loading()` in particular is true for
    `TransitionWindow` (a real zone load, seconds) and for `PageFlip` (a
    book, potentially forever), and a caller that cannot tell those two
    apart has to treat both as fatal or both as transient. Neither is
    right.
    """
    try:
        if await client.in_battle():
            return BLOCK_DUEL
    except Exception:
        return BLOCK_UNREADABLE
    try:
        if await is_visible_by_path(client, advance_dialog_path):
            return BLOCK_DIALOGUE
    except Exception:
        pass
    try:
        if not await client.is_loading():
            return BLOCK_NONE
    except Exception:
        return BLOCK_UNREADABLE
    # Loading, and now the interesting half: which kind.
    try:
        view = await client.get_world_view_window()
        if await _has_child(view, "TransitionWindow"):
            return BLOCK_TRANSITION
        if await _has_child(client.root_window, "PageFlip"):
            return BLOCK_PAGEFLIP
    except Exception:
        pass
    return BLOCK_LOADING


def _wait_budget(kind: str) -> float:
    return TP_LOADING_WAIT if kind in LOADING_BLOCKS else TP_FREE_WAIT


async def wait_until_free(client, timeout: float = None,
                          interval: float = 0.25) -> str:
    """The kind still blocking, or `BLOCK_NONE` once the wizard is free.

    Bounded, and the bound is the point -- see `WAITFOR_TIMEOUTS` in
    `deimoslang/vm.py` for what an unbounded poll on a game condition
    costs. The bound depends on what is blocking: a duel is not waited
    on at all, a dialogue box gets `TP_FREE_WAIT`, and a loading flag
    gets `TP_LOADING_WAIT` because a real zone load can use it.
    """
    waited = 0.0
    while True:
        kind = await blocked_by(client)
        if kind == BLOCK_NONE:
            return BLOCK_NONE
        if kind == BLOCK_DUEL:
            return BLOCK_DUEL           # not transient, and not teleportable
        limit = _wait_budget(kind) if timeout is None else timeout
        if waited >= limit:
            return kind
        await asyncio.sleep(interval)
        waited += interval


#: Called as (landed, how, zone) when `navmap_tp` finishes. wizAi sets
#: this so a teleport that did not land reaches the run's log; left as
#: None the patch changes nothing but the return value.
on_teleport_result = None


#: Called as (message, client) for something worth saying that is not an
#: outcome -- currently only the one place the loading gate is overridden,
#: which is a decision a human should be able to see us make.
on_teleport_note = None


def _tp_note(message: str, client=None) -> None:
    if on_teleport_note is not None:
        try:
            on_teleport_note(message, client)
        except Exception:
            pass


def _tp_result(landed: bool, how: str, zone: str = "", client=None) -> bool:
    if on_teleport_result is not None:
        try:
            on_teleport_result(bool(landed), how, zone, client)
        except Exception:
            pass
    return bool(landed)


# ---------------------------------------------------------------------------
# wizAi walk-only mode. When `walk_nav.walking()` is on, the teleport
# primitives below try the whole hop ON FOOT first -- A* over the zone's
# walk grid, leg-by-leg goto -- and only fall back to writing position
# memory when walking cannot deliver (per `walk_nav.fallback()`). The
# principle and its exceptions are documented in `walk_nav` itself.

#: Walk outcomes that settle the hop -- the teleport machinery is not
#: needed after any of these. `interrupted` is success by the same
#: contract as `_arrived`'s "no longer free / zone changed; done", and
#: `partial` is success because every caller re-issues navigation on its
#: next iteration, so covered ground composes into arrival.
_WALK_SETTLED = (walk_nav.WALK_ARRIVED, walk_nav.WALK_PARTIAL,
                 walk_nav.WALK_INTERRUPTED)


def _walk_result(outcome: str, detail: str, zone_name: str, client) -> bool:
    """A settled walk outcome, reported like any other landing kind."""
    if outcome == walk_nav.WALK_PARTIAL:
        return _tp_result(True, f"walk-partial ({detail})", zone_name, client)
    if outcome == walk_nav.WALK_INTERRUPTED:
        return _tp_result(True, "walk (interrupted)", zone_name, client)
    if detail.startswith("path end"):
        # As close as the mesh goes -- its own outcome kind (like
        # 'collision-short') so a systematically short walk shows in the
        # export instead of thinning away under the successes.
        return _tp_result(True, f"walk-short ({detail})", zone_name, client)
    return _tp_result(True, "walk", zone_name, client)


async def _walk_first(client: Client, target_xyz: XYZ, zone_name: str):
    """Try the hop on foot. Returns the final bool when walking settled
    it, or None when the caller should run its teleport machinery -- the
    fallback having already been spoken through `_tp_note`, except for
    an off-mesh target (script bumps aim there on purpose)."""
    outcome, detail = await walk_nav.walk_to(client, target_xyz)
    if outcome in _WALK_SETTLED:
        return _walk_result(outcome, detail, zone_name, client)
    if walk_nav.fallback() == walk_nav.FALLBACK_NEVER:
        return _tp_result(False, f"walk-only: {outcome} ({detail})",
                          zone_name, client)
    if not (outcome == walk_nav.WALK_UNREACHABLE
            and detail == walk_nav.DETAIL_OFF_MESH):
        _tp_note(f"walk fallback: {outcome} ({detail}) — teleporting "
                 f"instead", client)
    return None


async def nav_teleport(client: Client, xyz: XYZ) -> bool:
    """Mode-aware stand-in for a RAW positional `client.teleport(xyz)`.

    The script VM's `tp XYZ(...)` legs are navigation written as exact
    coordinates, so in walk mode they walk. Two deliberate differences
    from `_walk_first`'s routing:

    * An off-mesh target teleports RAW and silently -- the scripts' 116
      `tp XYZ(0, 100000, 0)`-style bumps rely on the game clamping an
      impossible position, and that trick has no walking equivalent.
    * The fallback is the raw teleport to the exact point the script
      asked for, not the collision solve -- the script knows its own
      coordinates better than the solver knows its intent.

    In teleport mode this is exactly the raw call it replaces: no result
    reporting, so the log does not change while the toggle is off.
    """
    if walk_nav.walking():
        try:
            zone_name = await client.zone_name()
        except Exception:
            zone_name = ""
        outcome, detail = await walk_nav.walk_to(client, xyz)
        if outcome in _WALK_SETTLED:
            return _walk_result(outcome, detail, zone_name, client)
        if (outcome == walk_nav.WALK_UNREACHABLE
                and detail == walk_nav.DETAIL_OFF_MESH):
            await client.teleport(xyz)
            return _tp_result(True, "direct (walk-only bump)",
                              zone_name, client)
        if walk_nav.fallback() == walk_nav.FALLBACK_NEVER:
            return _tp_result(False, f"walk-only: {outcome} ({detail})",
                              zone_name, client)
        _tp_note(f"walk fallback: {outcome} ({detail}) — teleporting "
                 f"instead", client)
        await client.teleport(xyz)
        return _tp_result(True, "direct (walk fallback)", zone_name, client)
    await client.teleport(xyz)
    return True


async def navmap_tp(client: Client, xyz: XYZ = None, leader_client: Client = None,
                    _walk_first_try: bool = True) -> bool:
    """wizAi patch: this now RETURNS whether the teleport landed.

    Upstream every `return` here is bare, including the `if not await
    is_free(client): return` on the first line -- so success, failure
    and never-even-attempted are the same answer, and nothing above can
    tell them apart. That is why deimoslang scripts wrap `tp` in
    unbounded retry loops (331 of them across the arc scripts wizAi was
    tested against): the primitive gives them nothing to check, so they
    poll the game's own windows and hope.

    It is also the reported failure that started all of this -- "one
    wizard might get through with a teleport, but the others might stop
    teleporting or get stuck". A teleport that silently did not land
    leaves the script issuing instructions for a place its wizard is not
    in, and neither the script nor wizAi could see it happen.

    Behaviour is unchanged: same teleports, same order, same fallbacks.
    Only the answer is new, plus `on_teleport_result` for a caller that
    wants to record it.
    """
    # TODO: What is leader_client meant to be for?
    blocker = await blocked_by(client)
    if blocker:
        # Upstream this is where the instruction is dropped, silently and
        # for any of four reasons. Wait instead -- and then answer each
        # reason on its own terms.
        blocker = await wait_until_free(client)
        if blocker in (BLOCK_DUEL, BLOCK_DIALOGUE, BLOCK_UNREADABLE):
            # Nothing a teleport can do about any of these. Say which.
            waited = "" if blocker == BLOCK_DUEL \
                else f" after {TP_FREE_WAIT:.0f}s"
            return _tp_result(False, describe_block(blocker) + waited,
                              client=client)
        if blocker in LOADING_BLOCKS:
            # A "loading screen" that has not ended in TP_LOADING_WAIT is
            # not a loading screen. Krokotopia's longest transition is a
            # few seconds; `PageFlip` left open is forever. Dropping the
            # teleport here is what produced nineteen identical failures
            # over five minutes while the wizard stood still, out of
            # combat, with no dialogue box and an NPC popup on screen --
            # a wizard that was plainly interactive.
            #
            # So push through. The cost of teleporting during a genuine
            # load is a write the zone load overwrites, which the
            # `check_success` fallbacks below already handle; the cost of
            # not doing it is the run stopping.
            _tp_note(f"{describe_block(blocker)} and had not cleared in "
                     f"{TP_LOADING_WAIT:.0f}s — teleporting anyway rather "
                     f"than dropping the instruction", client)
        elif blocker:
            return _tp_result(False,
                              f"{describe_block(blocker)} after "
                              f"{TP_FREE_WAIT:.0f}s", client=client)

    starting_zone = await client.zone_name() # for loading the correct wad and to walk to target as a last resort
    starting_xyz = await client.body.position()
    target_xyz = xyz if xyz is not None else await client.quest_position.position()

    def check_sigma(a: XYZ, b: XYZ, sigma=5.0):
        # check if a distance is more or less zero
        return calc_Distance(a, b) <= sigma

    async def check_success():
        # Check if the teleport succeeded. For this we want to have moved away from the starting position.
        await asyncio.sleep(1) # make sure we got useful information
        return not check_sigma(await client.body.position(), starting_xyz)

    async def finished_tp():
        return await check_success() or not await is_free(client) or await client.zone_name() != starting_zone

    if check_sigma(starting_xyz, target_xyz):
        return _tp_result(True, "already there", starting_zone, client)

    if _walk_first_try and walk_nav.walking():
        # wizAi walk-only mode: the hop goes on foot first. `_walk_first`
        # returns None when walking could not deliver -- then the teleport
        # machinery below runs as the fallback, exactly as before.
        out = await _walk_first(client, target_xyz, starting_zone)
        if out is not None:
            return out

    await client.teleport(target_xyz)
    if await finished_tp():
        return _tp_result(True, "direct", starting_zone, client)

    try:
        # attempt to use the nav data
        wad = await load_wad(starting_zone)
        nav_file = await wad.get_file("zone.nav")
        vertices, edges = parse_nav_data(nav_file)
    except:
        # Unable to load nav data. Fall back to primitive spiral pattern
        await fallback_spiral_tp(client, target_xyz)
        return _tp_result(await check_success(), "spiral (no nav data)",
                          starting_zone, client)

    # continuation of nav data tp, don't want to swallow potential exceptions in this section
    closest_vertex = vertices[0]
    lowest_distance = calc_Distance(closest_vertex, target_xyz)
    for i in range(1, len(vertices)):
        vertex = vertices[i]
        vert_dist = calc_Distance(vertex, target_xyz)
        if vert_dist < lowest_distance:
            closest_vertex = vertex
            lowest_distance = vert_dist

    max_depth = 3
    queue = [[closest_vertex]]
    relevant = set()
    while len(queue) > 0:
        path = queue.pop()
        v = path[-1]
        relevant.add(v)
        for neighbor in get_neighbors(v, vertices, edges):
            if neighbor in relevant or len(path) + 1 > max_depth:
                continue
            new_path = list(path)
            new_path.append(neighbor)
            queue.append(new_path)

    # average position of the vertices
    avg_xyz = XYZ(0, 0, 0)
    for v in relevant:
        avg_xyz.x += v.x
        avg_xyz.y += v.y
        avg_xyz.z += v.z
    avg_xyz = XYZ(avg_xyz.x / len(relevant), avg_xyz.y / len(relevant), avg_xyz.z / len(relevant))
    # vector from average xyz to target
    av = XYZ(target_xyz.x - avg_xyz.x, target_xyz.y - avg_xyz.y, avg_xyz.z - target_xyz.z)
    # midpoint of line from average point to target
    ap2 = XYZ(avg_xyz.x + av.x / 2, avg_xyz.y + av.y / 2, avg_xyz.z + av.z / 2)
    await client.teleport(ap2)
    if await check_success():
        if await is_free(client) and await client.zone_name() == starting_zone:
            await client.goto(target_xyz.x, target_xyz.y)
        return _tp_result(True, "nav midpoint", starting_zone, client)
    await client.teleport(avg_xyz) # average point
    if await check_success():
        if await is_free(client) and await client.zone_name() == starting_zone:
            await client.goto(target_xyz.x, target_xyz.y)
        return _tp_result(True, "nav average", starting_zone, client)
    await fallback_spiral_tp(client, target_xyz)
    return _tp_result(await check_success(), "spiral (nav exhausted)",
                      starting_zone, client)


# ---------------------------------------------------------------------------
# Deimos 3.14.0's collision teleport, ported. Everything from here to
# `collision_tp` is upstream's addition verbatim; `collision_tp` itself is
# adapted at its seams to this file's local contracts -- it RETURNS whether
# the teleport landed and reports through `on_teleport_result`, exactly like
# the navmap_tp above it (see that docstring for why), and a blocked client
# is handed to navmap_tp's wait machinery instead of silently dropped.
#
# NB: the zone.nav navigation *graph* (A* over vertices/edges) is deliberately
# NOT used for teleporting -- it's inaccurate in many zones (sparse, vertices
# on the wrong island / inside walls). Teleporting is driven purely by the
# zone's collision geometry: the walkable collision mesh + every collideable
# object (see ``collision_tp`` / ``collision_math``). ``parse_nav_data`` /
# ``get_neighbors`` survive for ``navmap_tp``, the fallback used when a zone
# ships no collision.bcd at all (and for every caller that keeps using it).

# The player's wall-clearance radius, clamped to a small collision-capsule range.
# The model footprint (and half-height) reflect the *visual* extent -- staff, cape,
# nameplate -- which is several times the body's real collision radius. Using that
# large value as wall clearance erodes narrow walkable corridors and throws the
# teleport far past the target, so we clamp it to a sane capsule size.
_PLAYER_RADIUS_MIN = 25.0
_PLAYER_RADIUS_MAX = 55.0


async def _resolve_player_radius(client: Client, zone_name: str) -> float:
    """Horizontal wall-clearance radius of the player's body, in world units.

    Pulls the player object's footprint radius (scaled by body scale) when it
    resolves, else the vertical half-height proxy, then a constant -- and clamps the
    result to ``[_PLAYER_RADIUS_MIN, _PLAYER_RADIUS_MAX]`` so an over-large visual
    footprint can't make the collision solve overshoot.
    """
    try:
        scale = await client.body.scale()
    except Exception:
        scale = 1.0
    radius = None
    try:
        from src import entity_collision

        tid = await client.client_object.template_id_full()
        r = await asyncio.to_thread(
            entity_collision.get_object_collider_radius, tid, zone_name
        )
        if r and r > 0:
            radius = r * scale
    except Exception:
        radius = None
    if radius is None:
        try:
            radius = (await client.body.height()) * scale * 0.5
        except Exception:
            radius = 45.0
    return max(_PLAYER_RADIUS_MIN, min(radius, _PLAYER_RADIUS_MAX))


# Retreat offsets (world units) from a blocked destination back toward the approach
# anchor, tried in order until a teleport sticks. The collision solver only knows the
# *modeled* geometry (collision.bcd walls + gamedata.bin solid colliders); warp /
# teleporter trigger volumes (e.g. AZ-TELEPORT-...) carry no solid-collision file yet
# still rubber-band you, so a geometrically-clear landing can be rejected. When that
# happens we step back along the approach line until we're clear of the object.
_RETREAT_STEPS = (70.0, 140.0, 230.0, 350.0, 520.0)


# navmap_tp's check_sigma default: "still within this many units of where we started"
# is proof the game sent us back. Same constant, same 3D distance, same meaning.
_TP_ORIGIN_SIGMA = 5.0


def _sent_back(pos: XYZ, origin: XYZ) -> bool:
    """navmap_tp's landing test, verbatim: it is a rejected teleport iff we have not
    moved away from where we started (``not check_success()`` there)."""
    return calc_Distance(pos, origin) <= _TP_ORIGIN_SIGMA


async def _arrived(client: Client, dest: XYZ, origin: XYZ = None, zone_before: str = None,
                   settle: float = 1.0, tol: float = 60.0) -> bool:
    """True if, after letting the server settle, the teleport to ``dest`` actually took.

    Two independent signals, because either one alone has a blind spot:

    * **Proximity** -- did we end up near ``dest``? Horizontal plane only: a rubber-band
      off a collider throws you far in x/y, while ``z`` always terrain-snaps and would
      otherwise cause false misses.
    * **Did the game send us back** -- ``_sent_back``, navmap_tp's check, and the one that
      catches a *silently* rejected teleport. If we're still sitting on ``origin``,
      nothing moved us, however close ``dest`` happens to be to that spot. Without it a
      retreat step that walks back toward the start eventually lands "within tolerance"
      of a player who never moved, and a failed teleport is reported as a success.

    Also like navmap_tp: a zone change or a client that is no longer free ends the check
    as done -- we can't verify or usefully retry through a loading screen or a battle, and
    retreating would only fight whatever moved us. Unreadable position -> assume success
    rather than thrash on a transient read error.
    """
    await asyncio.sleep(settle)
    try:
        if zone_before is not None and await client.zone_name() != zone_before:
            logger.debug(f"[collision_tp] {client.title}: zone changed during teleport; done")
            return True
        if not await is_free(client):
            logger.debug(f"[collision_tp] {client.title}: no longer free during teleport; done")
            return True
        pos = await client.body.position()
    except Exception:
        return True
    if origin is not None and not _sent_back(dest, origin):
        # dest is somewhere we'd have to move to reach, so staying put means rejection
        if _sent_back(pos, origin):
            logger.debug(
                f"[collision_tp] {client.title}: never left the starting position; "
                f"teleport to {dest} was rejected"
            )
            return False
    return math.hypot(pos.x - dest.x, pos.y - dest.y) <= tol


async def _teleport_once_verified(client: Client, dest: XYZ, anchor: XYZ,
                                  zone_before: str = None) -> bool:
    """One teleport to ``dest``, confirmed by ``_arrived``. No retreating."""
    if not await is_free(client):
        return False
    await client.teleport(dest)
    return await _arrived(client, dest, anchor, zone_before)


async def _retreat_toward(client: Client, dest: XYZ, anchor: XYZ,
                          zone_before: str = None) -> bool:
    """Back off from a bounced ``dest`` toward ``anchor`` in increasing steps until a
    landing sticks. Each retreat is verified, so one that clips a modeled wall just rolls
    to the next. True once a teleport sticks, False if every step bounced."""
    for back in _RETREAT_STEPS:
        point = calc_PointOn3DLine(anchor, dest, back)  # 'back' units from dest toward anchor
        if calc_Distance(point, dest) < 1.0:
            break  # anchor too close to retreat any further
        if not await is_free(client):
            return False
        logger.debug(
            f"[collision_tp] {client.title}: destination bounced; retreating {back:.0f}u "
            f"toward start -> {point}"
        )
        await client.teleport(point)
        if await _arrived(client, point, anchor, zone_before):
            return True
    return False


async def teleport_collision_verified(client: Client, dest: XYZ, anchor: XYZ,
                                      zone_before: str = None) -> bool:
    """Teleport to ``dest`` and confirm the server accepted it; on a rubber-band,
    retreat toward ``anchor`` in increasing steps until a landing sticks.

    The decisive collision teleport assumes the destination clears every obstacle, but
    unmodeled warp volumes still bounce you. Returns True once a teleport sticks, False
    if every attempt bounced (caller should fall back to navmap_tp).

    ``anchor`` doubles as the origin for the did-we-move check in ``_arrived``, so a
    retreat that lands back at the player's feet is counted as the failure it is instead
    of passing the proximity test.
    """
    if zone_before is None:
        try:
            zone_before = await client.zone_name()
        except Exception:
            zone_before = None
    if await _teleport_once_verified(client, dest, anchor, zone_before):
        return True
    return await _retreat_toward(client, dest, anchor, zone_before)


# Don't bother walking gaps smaller than this -- the teleport already put us in range.
#
# wizAi patch: upstream sets 120, "in range" meaning INTERACTION range --
# right for talk/collect, wrong for a defeat quest, where the wizard has
# to stand in the mobs' AGGRO radius before anything happens. The
# collision landing is by construction the nearest CLEAR point, which is
# systematically outside a mob pack, and at rev dbced750 that composed
# into a stall: the preset teleported to "Defeat Jacques the Scratcher"
# over and over, each landing a reported success ~a hundred units short,
# no mob ever pulled, and the script looped its safe-area/quest-teleport
# cycle for four minutes. navmap_tp never had this failure because it
# lands ON the marker, mobs and all. Twenty units is inside both
# interaction and aggro range, and the A* walk this enables costs
# nothing measurable at these distances.
_WALK_GAP_MIN = 20.0

#: wizAi: how far from the TARGET a finished collision teleport may leave the wizard
#: before the landing counts as SHORT. The teleport's contract to the script is not
#: "a teleport happened" -- it is "the wizard now stands at the objective", because the
#: script's very next instruction assumes it: rev e786b716's preset teleported to a
#: dungeon sigil, immediately checked the press-X prompt to classify the interactable,
#: read nothing (the wizard's heartbeat put him 270 units out), declared "not a
#: dungeon", and opened its next loop iteration by teleporting everyone away to its
#: safe area -- three times over, ~13s each, before one attempt happened to stick.
#: The operator: "it shouldnt take a billion attempts to enter a dungeon". 60 is
#: comfortably inside interaction range and outside the landing scatter a verified
#: teleport normally produces.
_LANDED_NEAR = 60.0
#: ...and the farthest a landing check will WALK to close the gap. Beyond this the
#: landing did not merely scatter -- something rejected or relocated the wizard -- and
#: a blind cross-zone hike toward the marker is how wizards die in the street. The
#: gap is reported instead ('collision-short'), where the export makes it visible.
_LANDED_WALK_CAP = 800.0


async def _walk_remaining_to_target(client: Client, target_xyz: XYZ, world, zone_name: str,
                                    player_radius: float, avoid=None) -> bool:
    """Walk the final stretch on foot when the teleport had to stop short of a target that
    is itself walk-reachable.

    Some objects block a *teleport* landing (the server rubber-bands you) while the navmesh
    runs continuously through them -- the WC Drains chamber cylinders are exactly this: the
    collision solve correctly lands at the nearest teleport-valid point, but that's hundreds
    of units out, past activation range. We close the rest on foot by **A* over the zone's
    walk-valid hex nodes** (lazy, cached) -- a node-to-node path that routes around obstacles,
    not a single straight `goto`. Walk-valid nodes are more permissive than teleport-valid
    (the cylinder interior is walkable) but still clear of static entity colliders, so we
    never path onto a teleporter pad. We only refine onto the exact target if the target's own
    node is walkable. No path / read error -> stay put. Best-effort.

    ``avoid`` is the set of solid footprints that just bounced a teleport (see
    ``blocking_volumes_at``). Walk nodes deliberately ignore bcd-collider interiors, which is
    right for the Drains cylinders but wrong for a statue the target is standing against: the
    A* path runs straight through it and the final ``goto`` drives into it. When ``avoid`` is
    given we stop at the last waypoint outside those footprints and skip the exact-target
    refinement. It is only ever passed after the game has rejected a landing, so ordinary
    teleports keep the full walk.

    wizAi patch: RETURNS whether the walk DELIBERATELY stopped short of the target --
    truncated at an avoid footprint, target on a static collider, no on-foot path, or a
    read/plan error. The caller uses this to decide whether a still-open gap may be closed
    with one last straight approach (see ``collision_tp``'s landing check): a walk that chose
    to stop must not be overridden, a walk that believed it finished may be."""
    try:
        pos = await client.body.position()
        gap = ((pos.x - target_xyz.x) ** 2 + (pos.y - target_xyz.y) ** 2) ** 0.5
        if gap <= _WALK_GAP_MIN:
            return False
        from src.collision_math import get_walk_grid
        from src import entity_collision

        extra = entity_collision.build_zone_static_shapes(zone_name, None)

        def _plan():
            grid = get_walk_grid(world, zone_name, extra, player_radius)
            tq = grid.to_hex(target_xyz.x, target_xyz.y)
            if grid.walk_z(*tq) is None:
                return None, False  # target itself isn't walk-reachable (on a pad/boat)
            return grid.find_walk_path(pos, target_xyz), True

        path, target_walkable = await asyncio.to_thread(_plan)
        if not target_walkable:
            # The target sits on a static collider (teleporter pad/boat). The teleport landing is
            # already the closest we can stand; walking toward it would only loop around the pad.
            logger.debug(
                f"[collision_tp] {client.title}: target not walk-reachable (static collider); "
                f"staying at the teleport landing {gap:.0f}u out"
            )
            return True
        if not path:
            logger.debug(
                f"[collision_tp] {client.title}: {gap:.0f}u short of target but no on-foot path; "
                f"staying at the teleport point"
            )
            return True
        walk = path[1:]  # skip the start node (~ current position)
        refine = True
        if avoid:
            from shapely.geometry import Point as _Point

            # wizAi patch: which KIND of solid bounced us? When the
            # TARGET ITSELF sits inside the volume, the volume is the
            # destination rather than an obstacle -- the game aims the
            # quest arrow INTO zone doors, service lifts and warp
            # volumes, whose frames carry ordinary collision that
            # rejects a teleport landing while welcoming a wizard on
            # foot. Walking in is how the transition fires. Rev
            # 66a4fe5b is the cost of treating them like statues:
            # 'collision (strict re-solve)' landed both wizards 103
            # units from a marker pointing into the Scotland Yard
            # service lift, the truncation parked them at its edge,
            # and the script teleport-looped against a door it only
            # needed to walk through. A target OUTSIDE the footprint
            # keeps upstream's statue rule -- stop at the edge, since
            # grinding into a wall face buys nothing.
            if any(fp.contains(_Point(target_xyz.x, target_xyz.y))
                   for fp in avoid):
                logger.debug(
                    f"[collision_tp] {client.title}: the target sits inside "
                    f"the volume that bounced the teleport -- treating it "
                    f"as a door and walking in"
                )
            else:
                kept = []
                for wp in walk:
                    if any(fp.contains(_Point(wp[0], wp[1])) for fp in avoid):
                        break  # stop at the edge of the solid instead of walking into it
                    kept.append(wp)
                if len(kept) != len(walk):
                    logger.debug(
                        f"[collision_tp] {client.title}: walk truncated at "
                        f"{len(kept)}/{len(walk)} waypoints -- the rest runs "
                        f"into the collider that bounced the teleport"
                    )
                    refine = False
                walk = kept
        logger.debug(
            f"[collision_tp] {client.title}: walking the final {gap:.0f}u via {len(walk)} "
            f"A* waypoints to the target"
        )
        for (wx, wy, _wz) in walk:
            if not await is_free(client):
                return True
            await client.goto(wx, wy)
        if refine and await is_free(client):  # refine onto the exact (walk-reachable) target
            await client.goto(target_xyz.x, target_xyz.y)
        return not refine
    except Exception as e:
        logger.debug(f"[collision_tp] {client.title}: final walk skipped ({e!r})")
        return True


# Zones whose collision/walkability caches are built or being built, so the background
# pre-warm and an actual teleport don't both rebuild the same zone.
_prewarmed_zones: set = set()


async def prewarm_zone(client: Client, zone_name: str = None) -> None:
    """Build the zone's collision + walkability caches in the BACKGROUND so the first teleport
    there is instant. Idempotent per zone, best-effort -- call it on client hook and on zone
    change (during the loading screen) so the work is finished before the player teleports.

    The heavy one-time costs all run here off the event loop and are memoized per zone: the
    precise resolver init (~0.8s, only on the very first call of a session), the navmesh
    triangle index, the static-collision shapes, and the hex grid. Afterwards a teleport in the
    zone is just cache hits plus a few node probes (~ms)."""
    zone = None
    try:
        zone = zone_name or await client.zone_name()
        if not zone or zone in _prewarmed_zones:
            return
        _prewarmed_zones.add(zone)
        from src.collision import CollisionWorld, get_collision_data
        from src.collision_math import get_walk_grid
        from src import entity_collision

        collision_data = await get_collision_data(client, zone)

        def _build():
            world = CollisionWorld()
            world.load(collision_data)
            extra = entity_collision.build_zone_static_shapes(zone, None)
            get_walk_grid(world, zone, extra, 45.0)

        await asyncio.to_thread(_build)
        logger.debug(f"[prewarm] collision caches ready for '{zone}'")
    except Exception as e:
        if zone:
            _prewarmed_zones.discard(zone)  # allow a later attempt to retry
        logger.debug(f"[prewarm] skipped ({e!r})")


async def collision_tp(client: Client, xyz: XYZ = None, leader_client: Client = None) -> bool:
    """Teleport by solving the zone's collision geometry -- a single, decisive teleport.

    Loads the zone collision data, computes (in a 2D slice at the target's height)
    the nearest point that lies on walkable mesh and clears every collision object,
    and teleports there exactly once. Because that point is geometrically guaranteed
    to be outside all walls, there's no trial-and-error: it's first-time-every-time.

    Only when the geometry can't be solved -- no collision data for the zone, a target
    outside the loaded area of interest, or a solve/teleport error -- does it fall back
    to the proven navmap_tp. Debug logs report exactly which path ran.

    wizAi patch, same shape as navmap_tp's: this RETURNS whether the
    teleport landed and reports every outcome through `on_teleport_result`.
    A client that is not free is handed straight to navmap_tp, whose
    wait-until-free machinery answers each blocker on its own terms instead
    of upstream's silent drop -- the lost instruction that started all of
    this. The fallback also goes through navmap_tp, which reports itself.
    """
    if not await is_free(client):
        return await navmap_tp(client, xyz, leader_client)

    target_xyz = xyz if xyz is not None else await client.quest_position.position()
    starting_xyz = await client.body.position()
    try:
        zone_name = await client.zone_name()
    except Exception:
        zone_name = ""
    logger.debug(
        f"[collision_tp] {client.title}: target {target_xyz} in '{zone_name}' "
        f"(from {'arg' if xyz is not None else 'quest_position'}); "
        f"start {starting_xyz} ({calc_Distance(starting_xyz, target_xyz):.0f}u away)"
    )
    if calc_Distance(starting_xyz, target_xyz) <= 5.0:
        return _tp_result(True, "already there", zone_name, client)

    walked = False
    if walk_nav.walking():
        # wizAi walk-only mode: try the whole hop on foot before any of
        # the teleport machinery. On a settled walk this is the answer;
        # otherwise fall through -- and remember, so the navmap fallback
        # at the bottom does not attempt the same failed walk twice.
        out = await _walk_first(client, target_xyz, zone_name)
        if out is not None:
            return out
        walked = True

    safe_xyz = None
    reason = "unavailable"
    try:
        # Imported lazily so shapely/numpy load only when collision TP is actually
        # used, and any import error degrades to navmap rather than breaking import.
        from src.collision import CollisionWorld, get_collision_data
        from src.collision_math import find_walkable_teleport_point
        from src import entity_collision

        player_radius = await _resolve_player_radius(client, zone_name)

        collision_data = await get_collision_data(client, zone_name)
        world = CollisionWorld()
        world.load(collision_data)

        # Rasterize the zone's walkability into a node grid (collision.bcd navmesh, height-aware
        # bcd colliders, and the WHOLE-zone static entity colliders -- teleporter pads, boats -- from
        # gamedata.bin, all known from files before we move) and pick the closest teleport-valid
        # point to the target. All file/CPU work, cached per zone, so it runs off the event loop.
        def _solve(strict=False):
            extra_shapes = entity_collision.build_zone_static_shapes(zone_name, None)
            return find_walkable_teleport_point(
                world, zone_name, target_xyz, extra_shapes=extra_shapes,
                player_radius=player_radius, strict=strict,
            )

        safe_xyz, reason = await asyncio.to_thread(_solve)
    except Exception as e:
        logger.debug(f"[collision_tp] {client.title}: collision solve errored ({e!r}); using navmap TP")
        safe_xyz = None

    async def _landed(label, walked_short=False):
        # wizAi: the landing check. A verified teleport plus a finished walk
        # is still not the contract -- STANDING AT the target is, and the
        # game can undo either after the fact: a sigil area that rubber-bands
        # a landing a beat after the verify window closes leaves the wizard
        # hundreds of units out while this function reports success. So
        # measure, and when the wizard is not there -- and the walk did not
        # deliberately stop short (a statue truncation is a decision, not a
        # failure) -- close the gap the way a player would, on foot, once.
        # Whatever gap remains is reported: a short landing becomes its own
        # outcome kind ('collision-short'), so the export shows the first one
        # instead of thinning it away under the successes.
        gap = None
        try:
            pos = await client.body.position()
            gap = ((pos.x - target_xyz.x) ** 2
                   + (pos.y - target_xyz.y) ** 2) ** 0.5
        except Exception:
            pass
        if (gap is not None and _LANDED_NEAR < gap <= _LANDED_WALK_CAP
                and not walked_short and await is_free(client)):
            logger.debug(
                f"[collision_tp] {client.title}: landed {gap:.0f}u from the "
                f"target after the walk; final approach on foot"
            )
            try:
                await client.goto(target_xyz.x, target_xyz.y)
                pos = await client.body.position()
                gap = ((pos.x - target_xyz.x) ** 2
                       + (pos.y - target_xyz.y) ** 2) ** 0.5
            except Exception:
                pass
        if gap is not None and gap > _LANDED_NEAR:
            return _tp_result(
                True, f"collision-short ({label}, {gap:.0f} from the target)",
                zone_name, client)
        return _tp_result(True, f"collision ({label})", zone_name, client)

    if safe_xyz is not None:
        moved = ((safe_xyz.x - target_xyz.x) ** 2 + (safe_xyz.y - target_xyz.y) ** 2) ** 0.5
        logger.debug(
            f"[collision_tp] {client.title}: collision TP ({reason}, r={player_radius:.0f}) -> "
            f"{safe_xyz} (moved {moved:.0f}u from target)"
        )
        if await _teleport_once_verified(client, safe_xyz, starting_xyz, zone_name):
            short = await _walk_remaining_to_target(client, target_xyz, world, zone_name, player_radius)
            return await _landed(reason, short)

        # The game refused a point the geometry called clear, so something solid is there
        # that the solve excused: ``ground_z_at`` ignores a volume whose vertical band contains
        # the target's own height, on the theory that a target standing inside a volume means
        # it's a structural shell rather than a wall. That's right for a tower's bounding box
        # and wrong for a statue you're standing against (AZ_Z11_TwinGiants: a 429u-tall
        # collision BOX whose base is level with the floor, target 1.5u off its face). We can't
        # tell those apart from the files -- the exemption is load-bearing for a large share of
        # ordinary walkable ground -- but a rejection is the game telling us which one this is,
        # so re-solve with every covering volume honoured and try that point.
        strict_xyz = None
        try:
            strict_xyz, strict_reason = await asyncio.to_thread(_solve, True)
        except Exception as e:
            logger.debug(f"[collision_tp] {client.title}: strict re-solve errored ({e!r})")
        if strict_xyz is not None and calc_Distance(strict_xyz, safe_xyz) > 5.0:
            moved = ((strict_xyz.x - target_xyz.x) ** 2 + (strict_xyz.y - target_xyz.y) ** 2) ** 0.5
            logger.debug(
                f"[collision_tp] {client.title}: rejected -> strict re-solve ({strict_reason}) "
                f"-> {strict_xyz} (moved {moved:.0f}u from target)"
            )
            if await _teleport_once_verified(client, strict_xyz, starting_xyz, zone_name):
                def _blockers():
                    from src.collision_math import blocking_volumes_at
                    return blocking_volumes_at(world, zone_name, target_xyz, player_radius)

                try:
                    avoid = await asyncio.to_thread(_blockers)
                except Exception:
                    avoid = None
                short = await _walk_remaining_to_target(
                    client, target_xyz, world, zone_name, player_radius, avoid=avoid
                )
                return await _landed("strict re-solve", short)

        # Still bounced: an unmodeled warp volume rather than a mis-excused wall. Back off
        # along the approach line before giving up on the geometry entirely.
        if await _retreat_toward(client, safe_xyz, starting_xyz, zone_name):
            short = await _walk_remaining_to_target(client, target_xyz, world, zone_name, player_radius)
            return await _landed("retreat", short)
        logger.debug(
            f"[collision_tp] {client.title}: collision point never landed (unmodeled collider "
            f"or rejected teleport); falling back to navmap TP"
        )

    else:
        logger.debug(f"[collision_tp] {client.title}: no collision solution ({reason}); falling back to navmap TP")
    return await navmap_tp(client, xyz, leader_client, _walk_first_try=not walked)



def calc_chunks(points: list[XYZ], entity_distance: float = 3147.0) -> list[XYZ]:
    # Returns a list of center points of "chunks" of the map, as defined by the input points.
    min_pos = XYZ(0, 0, 0)
    max_pos = XYZ(0, 0, 0)

    # find the extremes, they act as corners
    for point in points:
        if point.x < min_pos.x:
            min_pos.x = point.x
        if point.y < min_pos.y:
            min_pos.y = point.x

        if point.x > max_pos.x:
            max_pos.x = point.x
        if point.y > max_pos.y:
            max_pos.y = point.y

    # we use an inscribed square for chunking so corners are correctly included, using circles makes dealing with them way more annnoying
    side_length = math.sqrt(2) * entity_distance
    half_side_length = side_length / 2

    # start half a side length into the base square
    min_pos.x += half_side_length
    min_pos.y += half_side_length
    max_pos.x -= half_side_length
    max_pos.y -= half_side_length

    def point_in_rect(top_left: XYZ, bottom_right: XYZ, point: XYZ) -> bool:
        return point.x >= top_left.x and point.x < bottom_right.x and point.y >= top_left.y and point.y < bottom_right.y

    # place the first square outside the area, it is adjusted at the start of the loop anyways
    current_point = XYZ(min_pos.x - side_length, min_pos.y, 0)
    chunk_points = []
    leftover_points = set(points)
    # Turning the given points into a grid would be more efficient than this algorithm
    while True:
        # move the center of the rectangle to next rectangle
        current_point.x += side_length
        if current_point.x - half_side_length > max_pos.x:
            # next row
            current_point.x = min_pos.x
            current_point.y += side_length
            if current_point.y - half_side_length > max_pos.y:
                # scanned until the end
                break

        # filter squares that do not contain any points
        square_top_left = XYZ(current_point.x - half_side_length, current_point.y - half_side_length, 0)
        square_bottom_right = XYZ(current_point.x + half_side_length, current_point.y + half_side_length, 0)
        contained_points = set([])
        for p in leftover_points:
            if point_in_rect(square_top_left, square_bottom_right, p):
                contained_points.add(p)
        # a point cannot be in multiple squares at once
        leftover_points = leftover_points - contained_points

        if len(contained_points) > 0:
            chunk_points.append(copy(current_point))

    print(f'chunks:{len(chunk_points)}')
    return chunk_points


def calculate_yaw(xyz_1: XYZ, xyz_2: XYZ) -> float:
    # Calculates the yaw between 2 points.
    dx = xyz_1.x - xyz_2.x
    dy = xyz_1.y - xyz_2.y

    return math.atan2(dx, dy)


def calculate_pitch(xyz_1: XYZ, xyz_2: XYZ) -> float:
    # Find the reference vector
    x = xyz_2.x - xyz_1.x
    y = xyz_2.y - xyz_1.y
    z = xyz_2.z - xyz_1.z

    return -math.atan2(z, math.sqrt(x ** 2 + y ** 2))
